### PR TITLE
Create heart beat logic

### PR DESCRIPTION
**Pull request by tonyxuan2021**
- Added CORS at backend and I forgot to merge to main until today.

### CODE REVIEW

**Review by StudentCZ — COMMENTED** [review]
Did you just add CORS logic on to the PR?

**Review by yhus — APPROVED** [review]
Please try to separate style changes from actual code changes. Seems like everything but one line in this PR is a styling change?

**Comment by yhus** [comment]
Also, worth updating the PR title?

**Review by StudentCZ — APPROVED** [review]
Looks good after getting clarification for PR.

**Comment by tonyxuan2021** [comment]
Tested both endpoints on Dec 23 before merging into main branch. Safe to merge now.

**Pull request merged**
